#!/usr/bin/env bash
# setup_caddy.sh — generates Caddyfile and sets HTTPS_PORT for the CameraGestures server.
# Run from the server/ directory: bash setup_caddy.sh
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
DIM='\033[2m'
RESET='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CADDYFILE="$SCRIPT_DIR/Caddyfile"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Helpers ───────────────────────────────────────────────────────────────────

ask() {
    local label="$1" default="$2" value
    read -rp "$(printf '%b  %s%b [%b%s%b]: ' "$CYAN" "$label" "$RESET" "$DIM" "$default" "$RESET")" value
    printf '%s' "${value:-$default}"
}

section() {
    printf '\n%b── %s %b\n' "$BOLD" "$1" "$RESET"
}

# ── Require .env ──────────────────────────────────────────────────────────────

if [[ ! -f "$ENV_FILE" ]]; then
    printf '%bError: .env not found. Run bash setup_env.sh first.%b\n' "$RED" "$RESET"
    exit 1
fi

# ── Intro ─────────────────────────────────────────────────────────────────────

printf '\n%bCameraGestures — Caddy HTTPS setup%b\n' "$BOLD" "$RESET"
printf '%bPress Enter to accept the default shown in [brackets].%b\n' "$DIM" "$RESET"

# ── Prompts ───────────────────────────────────────────────────────────────────

section "HTTPS"

while true; do
    DOMAIN=$(ask "Domain name (e.g. gestures.example.com)" "")
    if [[ -n "$DOMAIN" ]]; then
        break
    fi
    printf '  %bDomain name is required.%b\n' "$RED" "$RESET"
done

HTTPS_PORT=$(ask "HTTPS port" "9443")

# ── Write Caddyfile ───────────────────────────────────────────────────────────

if [[ -f "$CADDYFILE" ]]; then
    backup="${CADDYFILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$CADDYFILE" "$backup"
    printf '\n  %bBacked up existing Caddyfile to %s%b\n' "$DIM" "$backup" "$RESET"
fi

cat > "$CADDYFILE" <<EOF
# Generated by setup_caddy.sh on $(date)
$DOMAIN {
    reverse_proxy server:8000
}
EOF

printf '\n%bCaddyfile written to %s%b\n' "$GREEN" "$CADDYFILE" "$RESET"

# ── Update HTTPS_PORT in .env ─────────────────────────────────────────────────

if grep -q '^HTTPS_PORT=' "$ENV_FILE"; then
    sed -i.bak "s|^HTTPS_PORT=.*|HTTPS_PORT=$HTTPS_PORT|" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
else
    printf '\n# ── Caddy HTTPS ──────────────────────────────────────────────────────────────\n' >> "$ENV_FILE"
    printf 'HTTPS_PORT=%s\n' "$HTTPS_PORT" >> "$ENV_FILE"
fi

printf '%bHTTPS_PORT=%s added to .env%b\n' "$GREEN" "$HTTPS_PORT" "$RESET"

# ── Summary ───────────────────────────────────────────────────────────────────

printf '\n%b┌─────────────────────────────────────────────────────────────┐%b\n' "$BOLD" "$RESET"
printf '%b│  Caddy configuration                                        │%b\n' "$BOLD" "$RESET"
printf '%b└─────────────────────────────────────────────────────────────┘%b\n' "$BOLD" "$RESET"
printf '\n  Domain:     %b%s%b\n' "$YELLOW" "$DOMAIN" "$RESET"
printf '  HTTPS port: %b%s%b\n' "$YELLOW" "$HTTPS_PORT" "$RESET"

printf '\n%bNote:%b Port 80 must be free and reachable from the internet\n' "$YELLOW" "$RESET"
printf '  for automatic TLS certificate issuance (ACME HTTP-01 challenge).\n'

printf '\nOpen the firewall:\n'
printf '  %bsudo ufw allow 80%b\n' "$CYAN" "$RESET"
printf '  %bsudo ufw allow %s%b\n' "$CYAN" "$HTTPS_PORT" "$RESET"

printf '\nStart with Caddy:\n'
printf '  %bdocker compose -f docker-compose.yml -f docker-compose.caddy.yml up --build -d%b\n\n' "$CYAN" "$RESET"

printf 'Update the iOS app Server URL to:\n'
printf '  %bhttps://%s:%s%b\n\n' "$CYAN" "$DOMAIN" "$HTTPS_PORT" "$RESET"
