#!/usr/bin/env bash
# setup_env.sh — interactive .env generator for the CameraGestures training server.
# Run from the server/ directory: bash setup_env.sh
set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
DIM='\033[2m'
RESET='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Helpers ───────────────────────────────────────────────────────────────────

# Ask a question with a default value; return the user's answer or the default.
ask() {
    local label="$1" default="$2" value
    read -rp "$(printf '%b  %s%b [%b%s%b]: ' "$CYAN" "$label" "$RESET" "$DIM" "$default" "$RESET")" value
    printf '%s' "${value:-$default}"
}

# Generate a cryptographically random hex string (64 chars = 32 bytes).
generate_secret() {
    if command -v openssl &>/dev/null; then
        openssl rand -hex 32
    else
        python3 -c "import secrets; print(secrets.token_hex(32))"
    fi
}

section() {
    printf '\n%b── %s %b\n' "$BOLD" "$1" "$RESET"
}

# ── Existing .env check ───────────────────────────────────────────────────────

if [[ -f "$ENV_FILE" ]]; then
    printf '%b\nWarning: .env already exists at %s%b\n' "$YELLOW" "$ENV_FILE" "$RESET"
    read -rp "$(printf '%b  Overwrite it? [y/N]: %b' "$YELLOW" "$RESET")" overwrite
    if [[ "${overwrite,,}" == "y" ]]; then
        backup="${ENV_FILE}.bak.$(date +%Y%m%d_%H%M%S)"
        cp "$ENV_FILE" "$backup"
        printf '  Backed up to %b%s%b\n' "$DIM" "$backup" "$RESET"
    else
        printf '\nAborted — existing .env was not modified.\n'
        exit 0
    fi
fi

# ── Intro ─────────────────────────────────────────────────────────────────────

printf '\n%bCameraGestures — training server setup%b\n' "$BOLD" "$RESET"
printf '%bPress Enter to accept the default shown in [brackets].%b\n' "$DIM" "$RESET"

# ── Server ────────────────────────────────────────────────────────────────────

section "Server"
HOST=$(ask "Bind address" "0.0.0.0")
PORT=$(ask "Port" "8000")

# ── Storage ───────────────────────────────────────────────────────────────────

section "Storage"
DATA_DIR=$(ask "Data directory (use an absolute path on a VPS)" "data")

# ── Training ──────────────────────────────────────────────────────────────────

section "Training"
AUTO_TRAIN_THRESHOLD=$(ask "Auto-train threshold (examples per gesture)" "10")

while true; do
    TRAINER=$(ask "Trainer backend (rf_mlp / lstm)" "rf_mlp")
    if [[ "$TRAINER" == "rf_mlp" || "$TRAINER" == "lstm" ]]; then
        break
    fi
    printf '  %bInvalid value. Choose rf_mlp or lstm.%b\n' "$RED" "$RESET"
done

MAX_MODEL_VERSIONS=$(ask "Max model versions to keep on disk" "5")

# ── Authentication ────────────────────────────────────────────────────────────

section "Authentication"

# JWT_SECRET is always auto-generated — there is no reason for a human to type it.
JWT_SECRET=$(generate_secret)
printf '  %bJWT_SECRET%b  auto-generated ✓\n' "$DIM" "$RESET"

# REGISTRATION_TOKEN — ask or generate.
printf '\n'
read -rp "$(printf '%b  Registration token%b (Enter to auto-generate): ' "$CYAN" "$RESET")" REGISTRATION_TOKEN
if [[ -z "$REGISTRATION_TOKEN" ]]; then
    REGISTRATION_TOKEN=$(generate_secret)
    printf '  %bGenerated registration token ✓%b\n' "$DIM" "$RESET"
fi

# ── Write .env ────────────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Generated by setup_env.sh on $(date)
# Do NOT commit this file — it contains secrets.

# ── Server ────────────────────────────────────────────────────────────────────
HOST=$HOST
PORT=$PORT

# ── Storage ───────────────────────────────────────────────────────────────────
# Use an absolute path when deploying to a VPS, e.g. /opt/cameragestures/data
DATA_DIR=$DATA_DIR

# ── Training ──────────────────────────────────────────────────────────────────
AUTO_TRAIN_THRESHOLD=$AUTO_TRAIN_THRESHOLD
TRAINER=$TRAINER
MAX_MODEL_VERSIONS=$MAX_MODEL_VERSIONS

# ── Authentication ────────────────────────────────────────────────────────────
# JWT_SECRET: signs all tokens — keep secret, rotate to invalidate all devices.
JWT_SECRET=$JWT_SECRET
# REGISTRATION_TOKEN: pre-shared secret the iOS app presents to obtain a JWT.
REGISTRATION_TOKEN=$REGISTRATION_TOKEN
EOF

chmod 600 "$ENV_FILE"

# ── Summary ───────────────────────────────────────────────────────────────────

printf '\n%b.env written to %s%b\n' "$GREEN" "$ENV_FILE" "$RESET"
printf '%b(permissions set to 600 — readable only by you)%b\n' "$DIM" "$RESET"

printf '\n%b┌─────────────────────────────────────────────────────────────┐%b\n' "$BOLD" "$RESET"
printf '%b│  Credentials — save these somewhere safe                    │%b\n' "$BOLD" "$RESET"
printf '%b└─────────────────────────────────────────────────────────────┘%b\n' "$BOLD" "$RESET"
printf '\n  %bREGISTRATION_TOKEN%b\n  %s\n' "$YELLOW" "$RESET" "$REGISTRATION_TOKEN"
printf '\n  %bJWT_SECRET%b\n  %s\n' "$YELLOW" "$RESET" "$JWT_SECRET"
printf '\n%b──────────────────────────────────────────────────────────────%b\n' "$DIM" "$RESET"
printf 'Enter the REGISTRATION_TOKEN in the iOS app:\n'
printf '  %bSettings → Server → Registration Token%b\n\n' "$CYAN" "$RESET"
printf 'Start the server:\n'
printf '  %bdocker compose up --build -d%b\n\n' "$CYAN" "$RESET"
