#!/usr/bin/env bash
# setup_caddy.sh — generates Caddyfile and sets HTTPS_PORT / CF_API_TOKEN for the
# CameraGestures server.  Uses Cloudflare DNS-01 challenge — ports 80 and 443
# do not need to be free.
# Run from the server/ directory: bash setup_caddy.sh
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
DIM='\033[2m'
RESET='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CADDYFILE="$SCRIPT_DIR/Caddyfile"
ENV_FILE="$SCRIPT_DIR/.env"

# ── Helpers ───────────────────────────────────────────────────────────────────

ask() {
    local label="$1" default="$2" value
    read -rp "$(printf '%b  %s%b [%b%s%b]: ' "$CYAN" "$label" "$RESET" "$DIM" "$default" "$RESET")" value
    printf '%s' "${value:-$default}"
}

ask_secret() {
    local label="$1" value
    printf '%b  %s%b (input hidden — paste and press Enter): ' "$CYAN" "$label" "$RESET" >&2
    read -rs value
    printf '\n' >&2
    if [[ -n "$value" ]]; then
        printf '  %bReceived (%d chars) ✓%b\n' "$DIM" "${#value}" "$RESET" >&2
    fi
    printf '%s' "$value"   # stdout only — this is what the caller captures
}

# set_env: safely writes or updates a key=value line in .env.
# Uses grep -v + append to avoid sed special-character issues.
set_env() {
    local key="$1" val="$2" tmp
    tmp="${ENV_FILE}.tmp"
    if grep -q "^${key}=" "$ENV_FILE"; then
        grep -v "^${key}=" "$ENV_FILE" > "$tmp"
        mv "$tmp" "$ENV_FILE"
    fi
    printf '%s=%s\n' "$key" "$val" >> "$ENV_FILE"
}

section() {
    printf '\n%b── %s %b\n' "$BOLD" "$1" "$RESET"
}

# ── Require .env ──────────────────────────────────────────────────────────────

if [[ ! -f "$ENV_FILE" ]]; then
    printf '%bError: .env not found. Run bash setup_env.sh first.%b\n' "$RED" "$RESET"
    exit 1
fi

# ── Intro ─────────────────────────────────────────────────────────────────────

printf '\n%bCameraGestures — Caddy HTTPS setup%b\n' "$BOLD" "$RESET"
printf '%bUses Cloudflare DNS-01 — ports 80/443 do not need to be free.%b\n' "$DIM" "$RESET"
printf '%bPress Enter to accept the default shown in [brackets].%b\n' "$DIM" "$RESET"

# ── Prompts ───────────────────────────────────────────────────────────────────

section "HTTPS"

while true; do
    DOMAIN=$(ask "Domain name (e.g. gestures.example.com)" "")
    if [[ -n "$DOMAIN" ]]; then break; fi
    printf '  %bDomain name is required.%b\n' "$RED" "$RESET"
done

HTTPS_PORT=$(ask "HTTPS port" "9443")

section "Cloudflare API token"
printf '  Create one at: %bhttps://dash.cloudflare.com/profile/api-tokens%b\n' "$DIM" "$RESET"
printf '  Template: %bEdit zone DNS%b → limit to zone %b%s%b\n\n' "$DIM" "$RESET" "$DIM" "$(printf '%s' "$DOMAIN" | rev | cut -d. -f1-2 | rev)" "$RESET"

while true; do
    CF_API_TOKEN=$(ask_secret "Cloudflare API token")
    if [[ -n "$CF_API_TOKEN" ]]; then break; fi
    printf '  %bToken is required.%b\n' "$RED" "$RESET"
done

# ── Write Caddyfile ───────────────────────────────────────────────────────────

if [[ -f "$CADDYFILE" ]]; then
    backup="${CADDYFILE}.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$CADDYFILE" "$backup"
    printf '\n  %bBacked up existing Caddyfile to %s%b\n' "$DIM" "$backup" "$RESET"
fi

cat > "$CADDYFILE" <<EOF
# Generated by setup_caddy.sh on $(date)
$DOMAIN {
    tls {
        dns cloudflare {env.CF_API_TOKEN}
    }
    reverse_proxy server:8000
}
EOF

printf '\n%bCaddyfile written to %s%b\n' "$GREEN" "$CADDYFILE" "$RESET"

# ── Update .env ───────────────────────────────────────────────────────────────

# Add Caddy section header if neither key exists yet
if ! grep -q '^HTTPS_PORT=' "$ENV_FILE" && ! grep -q '^CF_API_TOKEN=' "$ENV_FILE"; then
    printf '\n# ── Caddy HTTPS ──────────────────────────────────────────────────────────────\n' >> "$ENV_FILE"
fi

set_env "HTTPS_PORT" "$HTTPS_PORT"
set_env "CF_API_TOKEN" "$CF_API_TOKEN"

printf '%bHTTPS_PORT and CF_API_TOKEN written to .env%b\n' "$GREEN" "$RESET"

# ── Summary ───────────────────────────────────────────────────────────────────

printf '\n%b┌─────────────────────────────────────────────────────────────┐%b\n' "$BOLD" "$RESET"
printf '%b│  Caddy configuration                                        │%b\n' "$BOLD" "$RESET"
printf '%b└─────────────────────────────────────────────────────────────┘%b\n' "$BOLD" "$RESET"
printf '\n  Domain:     %b%s%b\n' "$YELLOW" "$DOMAIN" "$RESET"
printf '  HTTPS port: %b%s%b\n' "$YELLOW" "$HTTPS_PORT" "$RESET"
printf '  DNS-01:     %bCloudflare%b\n' "$YELLOW" "$RESET"

printf '\nOpen the firewall:\n'
printf '  %bsudo ufw allow %s%b\n' "$CYAN" "$HTTPS_PORT" "$RESET"

printf '\nStart with Caddy (builds custom image on first run — takes ~1 min):\n'
printf '  %bdocker compose -f docker-compose.yml -f docker-compose.caddy.yml up --build -d%b\n\n' "$CYAN" "$RESET"

printf 'Update the iOS app Server URL to:\n'
printf '  %bhttps://%s:%s%b\n\n' "$CYAN" "$DOMAIN" "$HTTPS_PORT" "$RESET"
