workspace 'ModelTraining/ModelTraining.xcworkspace'
platform :ios, '16.0'
use_frameworks! :linkage => :static

# Declare all local pods for dependency resolution
pod 'HandGestureTypes', :path => 'HandGestureTypes'
pod 'HandsRecognizingModule', :path => 'HandsRecognizing'
pod 'GestureModelModule', :path => 'GestureModel' 
pod 'HandGestureRecognizingFramework', :path => 'HandGestureRecognizing'

target 'HandGestureRecognizingTests' do
  project 'HandGestureRecognizing/HandGestureRecognizing/HandGestureRecognizingFramework.xcodeproj'
  pod 'HandGestureTypes', :path => 'HandGestureTypes'
  pod 'HandsRecognizingModule', :path => 'HandsRecognizing'
  pod 'GestureModelModule', :path => 'GestureModel'
  pod 'HandGestureRecognizingFramework', :path => 'HandGestureRecognizing'
end

target 'ModelTrainingApp' do
  project 'ModelTraining/ModelTraining/ModelTrainingApp.xcodeproj'
  
  # App uses the top-level pod that includes all dependencies
  pod 'HandGestureRecognizingFramework', :path => 'HandGestureRecognizing'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['ENABLE_TESTABILITY'] = 'YES' if config.name == 'Debug'
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    user_project = aggregate_target.user_project
    user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    user_project.save
  end
end