platform :ios, '15.0'
use_frameworks! :linkage => :static

# Declare all local pods for dependency resolution
pod 'HandGestureTypes', :path => 'HandGestureTypes'
pod 'HandsRecognizingModule', :path => 'HandsRecognizing'
pod 'GestureModelModule', :path => 'GestureModel' 
pod 'HandGestureRecognizingFramework', :path => 'HandGestureRecognizing'

target 'ModelTrainingApp' do
  project 'ModelTraining/ModelTraining/ModelTrainingApp.xcodeproj'
  
  # App uses the top-level pod that includes all dependencies
  pod 'HandGestureRecognizingFramework', :path => 'HandGestureRecognizing'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end