platform :ios, '15.0'
workspace 'CameraGestures'

project 'ModelTraining/HandGestureTypes/HandGestureTypes.xcodeproj'
project 'HandsRecognizing/HandsRecognizing/HandsRecognizingModule.xcodeproj'
project 'GestureModel/GestureModel/GestureModelModule.xcodeproj'
project 'HandGestureRecognizing/HandGestureRecognizing/HandGestureRecognizingFramework.xcodeproj'
project 'ModelTraining/ModelTraining/ModelTrainingApp.xcodeproj'

abstract_target 'CameraGestures' do
  
  target 'HandsRecognizingModule' do
    project 'HandsRecognizing/HandsRecognizing/HandsRecognizingModule.xcodeproj'
    use_frameworks!
    pod 'MediaPipeTasksVision', '0.10.14'
  end
  
  target 'GestureModelModule' do
    project 'GestureModel/GestureModel/GestureModelModule.xcodeproj'
    use_frameworks!
  end
  
  target 'HandGestureRecognizingFramework' do
    project 'HandGestureRecognizing/HandGestureRecognizing/HandGestureRecognizingFramework.xcodeproj'
    use_frameworks!
    pod 'MediaPipeTasksVision', '0.10.14'
  end
  
  target 'ModelTrainingApp' do
    project 'ModelTraining/ModelTraining/ModelTrainingApp.xcodeproj'
    use_frameworks!
    #pod 'MediaPipeTasksVision', '0.10.14'
    # No MediaPipe here - gets it through framework dependencies
  end
  
  target 'HandGestureTypes' do
    project 'ModelTraining/HandGestureTypes/HandGestureTypes.xcodeproj'
    use_frameworks!
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
end